# 初始化所有变量
feature_value = {
    'report_no': "",  # 征信报告编号
    'report_time': "",  # 征信报告时间
    'live_address_type': 0,  # 个人房产数
    'unsettled_business_loan_org_cnt': 0,  # 未结清经营性贷款合作机构数
    'unsettled_consume_loan_org_cnt': 0,  # 未结清消费性贷款合作机构数
    'unsettled_house_loan_cnt': 0,  # 未结清房贷笔数
    'unsettled_car_loan_cnt': 0,  # 未结清车贷笔数
    'loan_status_abnorm_cnt': 0,  # 贷款账户状态异常笔数
    'unsettled_category_abnormal_cnt': 0,  # 贷款五级分类异常笔数
    'loan_now_overdue_cnt': 0,  # 贷款当前逾期笔数
    'loan_now_overdue_money': 0.0,  # 贷款当前逾期金额
    'business_loan_average_3year_overdue_cnt': 0,  # 近3年还款方式为分期偿还的经营性贷款连续逾期期数
    'rhzx_business_loan_3year_overdue_cnt': 0,  # 近3年经营性贷款本金逾期次数
    'settled_business_loan_overdue_amount': 0.0,  # 经营性贷款到期未归还金额
    'single_loan_3year_overdue_max_month': 0,  # 单笔贷款近3年内出现连续逾期最大期数
    'single_loan_overdue_2year_cnt': 0,  # 单笔贷款近2年内最大逾期总次数
    'mort_settle_loan_date': [],  # 房贷按揭已归还
    'mort_no_settle_loan_date': [],  # 房贷按揭未结清
    'per_org_type': [],  # 机构类型
    'per_balance': [],  # 金额
    'per_balance_prop': [],  # 占比
    'business_loan_type_balance': 0.0,  # 经营性贷款余额
    'business_loan_type_cnt': 0,  # 经营性在贷贷款笔数
    'consume_loan_type_balance': 0.0,  # 消费性贷款余额
    'consume_loan_type_cnt': 0,  # 消费性在贷贷款笔数
    'mortgage_loan_type_balance': 0.0,  # 住房贷款余额
    'mortgage_loan_type_cnt': 0,  # 住房在贷贷款笔数
    'bus_mortgage_loan_type_balance': 0.0,  # 商用住房贷款余额
    'bus_mortgage_loan_type_cnt': 0,  # 商用住房在贷贷款笔数
    'max_unsettled_consume_amt': 0.0,  # 消费性贷款借款金额最大值
    'house_total_loan_amt': 0.0,  # 房贷借款总额
    'if_house_pre_settled': 0,  # 房贷提前结清记录数量
    'annual_year': [],  # 年份
    'annual_bus_loan_amount': [],  # 经营性借款金额
    'annual_cousume_loan_amount': [],  # 消费性借款金额
    'annual_org_cnt': [],  # 机构家数
    'total_loan_amount_latest_year': 0.0,  # 近12个月放款总额
    'total_loan_amount_last_year': 0.0,  # 上一年放款总额
    'unsettled_loan_balance': 0.0,  # 在贷余额
    'house_loan_total_balance': 0.0,  # 住房贷款余额
    'bus_house_loan_total_balance': 0.0,  # 商用住房贷款余额
    'car_loan_total_balance': 0.0,  # 车贷余额
    'new_add_1y_loan_cnt': 0,  # 近12个月新增贷款笔数
    'new_add_1y_loan_amount': 0.0,  # 近12个月新增借款金额
    'new_add_1y_unsettle_loan_cnt': 0,  # 近12个月新增在贷贷款笔数
    'new_add_1y_unsettled_loan_balance': 0.0,  # 近12个月新增在贷余额
    'if_loan_amount_lt_20w': 0,  # 是否有3家（含）以上授信金额 <= 20万
    'org_change_cnt ': 0,  # 机构变化家数
    'guarantee_type': [],  # 担保方式
    'business_loan_guarantee_type_cnt': [],  # 笔数
    'guarantee_type_balance': [],  # 余额
    'guarantee_type_balance_prop': [],  # 余额占比
    'bus_loan_pledge_cnt': 0,  # 经营性贷款质押笔数
    'bus_loan_credit_guar_balance_prop': 0.0,  # 经营性贷款信用保证类在贷金额占比
    'bus_loan_mort_balance': 0.0,  # 经营性贷款抵押组合类在贷余额
    'bus_loan_mort_balance_prop': 0.0,  # 经营性贷款抵押组合类余额占比
    'single_bus_loan_overdue_2year_cnt': 0,  # 单笔经营性贷款近2年内最大逾期次数
    'single_consume_loan_overdue_2year_cnt': 0,  # 单笔消费性贷款近2年内最大逾期次数
    'loan_overdue_2year_total_cnt': 0,  # 总计贷款2年内逾期次数
    'large_loan_2year_overdue_cnt': 0,  # 经营性贷款2年内最大连续逾期次数
    'unsettled_consume_total_cnt': 0,  # 未结清消费性贷款笔数
    'loan_doubtful': 0,  # 疑似压贷机构数
    'unsettled_loan_agency_number': 0,  # 未结清贷款机构家数
    'unsettled_consume_total_amount': 0.0,  # 未结清消费性贷款总额
    'rhzx_business_loan_3year_ago_overdue_cnt': 0,  # 3年前经营性贷款本金逾期笔数
    'business_loan_average_3year_ago_overdue_cnt': 0,  # 3年前还款方式为分期偿还的经营性贷款最大连续逾期期数
    'mort_org_cnt': 0,  # 按揭贷款机构数
    'credit_guar_loan_cnt': 0,  # 信用贷款家数
    'single_loan_max_overdue_month': 0,  # 单笔贷款2年内最大连续逾期期数
    'credit_loan_total_balance_1year': 0.0,  # 申请人他行一年内到期信用类贷款余额
    'if_credit_card_record': 0,  # 贷记卡信息条数
    'activated_credit_card_cnt': 0,  # 贷记卡激活张数
    'credit_min_payed_number': 0,  # 贷记卡最低还款机构家数
    'credit_now_overdue_money': 0.0,  # 贷记卡当前逾期金额
    'credit_now_overdue_1k_money': 0.0,  # 贷记卡当前严重逾期金额
    'single_credit_overdue_2year_cnt': 0,  # 单笔贷记卡近2年内总逾期次数
    'single_credit_3year_overdue_max_month': 0,  # 单笔贷记卡近3年内出现连续逾期最大期数
    'credit_org_cnt': 0,  # 发卡机构数量
    'total_credit_loan_amount': 0.0,  # 贷记卡授信额度总额
    'total_credit_quota_used': 0.0,  # 已使用额度总额
    'total_credit_avg_used_6m': 0.0,  # 最近6个月平均使用额度总额
    'total_credit_usage_rate': 0.0,  # 总使用率
    'credit_status_bad_cnt': 0,  # 贷记卡账户出现过“呆账”
    'credit_status_legal_cnt': 0,  # 贷记卡账户状态存在“司法追偿”
    'credit_status_b_level_cnt': 0,  # 贷记卡账户状态存在“银行止付、冻结”
    'credit_overdue_2year_total_cnt': 0,  # 总计贷记卡2年内逾期次数
    'single_semi_credit_card_3year_overdue_max_month': 0,  # 准贷记卡最大逾期期数
    'single_semi_credit_overdue_2year_cnt': 0,  # 单张准贷记卡近2年内最大逾期次数
    'loan_scured_five_b_level_abnormality_cnt': 0,  # 对外担保五级分类存在“关注”笔数
    'loan_scured_five_a_level_abnormality_cnt': 0,  # 对外担保五级分类存在“次级、可疑、损失”笔数
    'loan_balance_due_soon': 0.0,  # 到期日在信用报告拉取时间后面2个月的余额
    'credit_query_3month_cnt': 0,  # 近3个月信用卡查询机构家数
    'loan_query_3month_cnt': 0,  # 近3个月贷款审批查询机构家数
    'self_query_6month_cnt': 0,  # 近6个月本行审批查询次数
    'self_guar_query_6month_cnt': 0,  # 近6个月本行担保资格审查次数
    'loan_query_1y_cnt': 0,  # 近1年贷款审批查询机构家数
    'guar_query_cnt': 0,  # 近3个月保前审查笔数
    'credit_review_query_cnt': 0,  # 近3个月资信审查笔数
    'max_query_cnt_15d': 0,  # 连续审批查询机构家数
    'loan_credit_query_1month_orgcnt_others': 0,  # 征信近1个月他行‘贷款审批’+‘信用卡审批’查询机构数
    'loan_credit_query_1month_cnt_others': 0,  # 征信近1个月他行‘贷款审批’+‘信用卡审批’查询次数
    'loan_credit_query_1month_cnt_own': 0,  # 征信近1个月本行‘贷款审批’+‘信用卡审批’查询次数
    'loan_credit_query_3month_cnt': 0,  # 近3个月审批查询机构家数
    'loan_credit_query_3month_orgcnt_others': 0,  # 征信近3个月他行‘贷款审批’+‘信用卡审批’查询机构数
    'loan_credit_query_3month_cnt_others': 0,  # 征信近3个月他行‘贷款审批’+‘信用卡审批’查询次数
    'loan_credit_query_3month_cnt_own': 0,  # 征信近3个月本行‘贷款审批’+‘信用卡审批’查询次数
    'per_debt_amt': 0.0,  # 个人征信负债余额
    'if_no_credit_record': 0,  # 是否白户
    'query_loan_approved_3m_org_cnt': 0,  # 近3个月贷款放款机构家数
    'query_loan_approved_3m_prob': 0.0,  # 近3个月贷款审批查询放款比例
    'loan_approved_rate_1y': 0.0,  # 近1年贷款查询放款比例
    'all_loan_account_cnt': 0,  # 贷款及其他账户总数
    'used_creditcard_balance': 0.0,  # 信用卡当前已用额度
    'ifexception': 'F',  # 贷记卡状态是否存在异常，默认F，不存在异常
    'foreignassurenum': 0  # 对外担保笔数
}
