
base_type_mapping = {
    "U_PERSONAL": "借款人",
    "U_PER_LG_COMPANY": "借款人作为法定代表人的企业",
    "U_PER_SH_H_COMPANY": "借款人作为股东的企业，占股>=50%",
    "U_PER_SH_M_COMPANY": "借款人作为股东的企业，占股>=25%且<50%",
    "U_PER_SP_PERSONAL": "借款人配偶",
    "U_PER_SP_LG_COMPANY": "借款人配偶作为法定代表人的企业",
    "U_PER_SP_SH_H_COMPANY": "借款人配偶作为股东的企业，占股>=50%",
    "U_PER_SP_SH_M_COMPANY": "借款人配偶作为股东的企业，占股>=25%且<50%",
    "U_PER_CT_COMPANY": "借款人作为企业实际控制人的企业",
    "U_PER_SP_CT_COMPANY": "借款人配偶作为企业实际控制人的企业",
    "U_PER_PARENTS_PERSONAL": "借款人父母",
    "U_PER_CHILDREN_PERSONAL": "借款人子女",
    "U_PER_PARTNER_PERSONAL": "借款人合伙人",
    "U_PER_GUARANTOR_PERSONAL": "借款人担保人",
    "U_PER_GUARANTOR_COMPANY": "借款人担保企业",
    "U_PER_CHAIRMAN_COMPANY": "借款人作为董事长的企业",
    "U_PER_SUPERVISOR_COMPANY": "借款人作为监事的企业",
    "U_PER_OTHER": "借款人其它关系",
    "U_PER_COMPANY_SH_PERSONAL": "借款人关联企业股东",
    "U_PER_COMPANY_FIN_PERSONAL": "借款人关联企业财务",
    "U_COMPANY": "借款企业",
    "U_COMPANY_SH_PERSONAL": "借款企业股东",
    "U_COM_LEGAL_PERSONAL": "借款企业法人",
    "U_COMPANY_SH_H_COMPANY": "借款企业作为股东的企业，占股>=50%",
    "U_COMPANY_SH_M_COMPANY": "借款企业作为股东的企业，占股>=25%且<50%",
    "U_COM_CT_PERSONAL": "借款企业实际控制人",
    "U_COM_CT_CT_COMPANY": "借款企业实际控制人作为企业实际控制人的企业",
    "U_COM_CT_LG_COMPANY": "借款企业实际控制人作为法定代表人的企业",
    "U_COM_CT_SH_H_COMPANY": "借款企业实际控制人作为股东的企业，占股>=50%",
    "U_COM_CT_SH_M_COMPANY": "借款企业实际控制人作为股东的企业，占股>=25%且<50%",
    "U_COM_CT_SP_PERSONAL": "借款企业实际控制人配偶",
    "U_COM_GUARANTOR_PERSONAL": "企业借款担保人",
    "U_COM_GUARANTOR_COMPANY": "企业借款担保企业",
    "U_COM_CT_SP_CT_COMPANY": "借款企业实际控制人配偶作为企业实际控制人的企业",
    "U_COM_CT_SP_LG_COMPANY": "借款企业实际控制人配偶作为企业法定代表人的企业",
    "U_COM_CT_SP_SH_H_COMPANY": "借款企业实际控制人配偶作为股东的企业，占股>=50%",
    "U_COM_CT_SP_SH_M_COMPANY": "借款企业实际控制人配偶作为股东的企业，占股>=25%且<50%",
    "U_COM_OTHER": "借款企业的其它关系",
    "U_COM_FIN_PERSONAL": "借款企业财务",

}
